## Multi-node configuration

## Elasticsearch configuration
network.host: <elasticsearch_ip>
node.name: <node_name>
cluster.name: <elastic_cluster>
cluster.initial_master_nodes:
        - <master_node_1>
        - <master_node_2>
        - <master_node_3>
discovery.seed_hosts:
        - <elasticsearch_ip_node1>
        - <elasticsearch_ip_node2>
        - <elasticsearch_ip_node3>
opendistro_security.nodes_dn:
        - CN=node-1,OU=Docu,O=Wazuh,L=California,C=US
        - CN=node-2,OU=Docu,O=Wazuh,L=California,C=US
        - CN=node-3,OU=Docu,O=Wazuh,L=California,C=US     

## Certificates creation
# Nodes certificates
nodes:
  - name: node-1
    dn: CN=node-1,OU=Docu,O=Wazuh,L=California,C=US
    ip:
      - <elasticsearch_ip_1>
  - name: node-2
    dn: CN=node-2,OU=Docu,O=Wazuh,L=California,C=US
    ip:
      - <elasticsearch_ip_2>
  - name: node-3
    dn: CN=node-3,OU=Docu,O=Wazuh,L=California,C=US
    ip:
      - <elasticsearch_ip_3>            
# Clients certificates
clients:
  - name: admin
    dn: CN=admin,OU=Docu,O=Wazuh,L=California,C=US
    admin: true
  - name: kibana
    dn: CN=kibana,OU=Docu,O=Wazuh,L=California,C=US    
  - name: filebeat
    dn: CN=filebeat,OU=Docu,O=Wazuh,L=California,C=US
