## Single-node configuration

## Elasticsearch configuration
network.host: <elasticsearch_ip>
node.name: node-1
cluster.initial_master_nodes: node-1

## Certificates creation
instances:
- name: "elasticsearch"
  ip:
  - "<elasticsearch_ip>"
- name: "filebeat"
  ip:
  - "<wazuh_server_ip>" 
- name: "kibana"
  ip:
  - "<kibana_ip>"     
